### ISSUE TITLE
Stopped working after update to Alfred 3.1.1

### ISSUE THREAD

**Issue by kamidev** [sotojuan/alfred-hex#1]
This worked great until I upgraded to Alfred 3.1.1 (which was released this weekend). After that,  typing "hex" doesn't seem to trigger the search.

**Comment by sotojuan** [comment]
Ha wow, bad luck! I'll update and read the changelog and try to figure it out. Thanks :-)

**Comment by sotojuan** [comment]
I've updated and it works for me :0 Can you share what's broken in yours? Maybe try to reinstall the package.

**Comment by kamidev** [comment]
Thank you. I just uninstalled and reinstalled the latest Alfred, activated Powerpack and reinstalled Alfred-hex. Still no luck. :-( 

![image](https://cloud.githubusercontent.com/assets/1655/18671034/c7c55f64-7f42-11e6-9418-d7167eb104b8.png)

**Comment by sotojuan** [comment]
I'll keep looking into it! Very weird.

**Comment by kamidev** [comment]
I am on OS X 10.11.6 and Node 6.6.0. Let me know if I can send you more detailed info.

**Comment by sotojuan** [comment]
If you can, try to install this: https://github.com/sindresorhus/alfred-npms and let me know if it also doesn't work. If it works, then not sure 😟 Uninstalling (`npm uninstall -g alfrex-hex`) and reinstalling one more time may help lol.

**Comment by kamidev** [comment]
Yes! Another re-install worked. Not sure why. But thanks a lot for your cool plugin!

![image](https://cloud.githubusercontent.com/assets/1655/18698939/2fe343f0-7fce-11e6-8fa3-09c34f4d2090.png)
